name: abo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #    git:
  #      url: git@github.com:cenaclesoft/hana.git
  riverpod:
  riverpod_annotation:

  lottie:

  #Architecture
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0

  #Authentication
  firebase_auth: ^4.10.0
  local_auth: ^2.1.7
  local_auth_android:
  local_auth_ios:
  pinput: ^3.0.0

  #Utils
  collection: ^1.17.2
  encrypt: ^5.0.1
  crypto: 3.0.3
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  mime: ^1.0.4
  path: ^1.8.3
  share_plus: ^7.1.0

  #Camera
  image_picker: ^1.0.4


  #Localization
  intl: ^0.18.1

  #Logger
  logger: ^2.0.2

  #Models
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  #Navigation
  auto_route: ^7.8.3

  #Network
  dio: ^5.3.2
  http: ^1.1.0
  retrofit: ^4.0.1
  stomp_dart_client: ^0.4.4

  #UI
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  percent_indicator: ^4.2.3
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  we_slide: ^2.4.0
  custom_refresh_indicator: ^2.2.1

  #Webview
  webview_flutter: ^4.2.4

  #Map
  flutter_naver_map: ^1.0.2
  geolocator: ^10.0.1

  #Notification
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  flutter_local_notifications: ^15.1.1

  #Else
  enum_to_string: ^2.0.1
  uuid: ^3.0.7
  url_launcher: ^6.1.14
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  qr_flutter: ^4.1.0
  screen_brightness: ^0.2.2
  infinite_scroll_pagination: ^4.0.0
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2
  scrollable_clean_calendar: ^1.4.1
  image: ^4.0.17
  file_picker: ^5.5.0
  file_selector: ^1.0.1
  path_provider: ^2.1.1
  charts_painter: ^3.1.1
  fluttertoast: ^8.2.2
  event_bus: ^2.0.0


# for test
#  device_preview: ^1.1.0


#dependency_overrides:
#  retrofit_generator:
#    path: ../generator

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  #Architecture
  riverpod_generator: ^2.2.6
  riverpod_lint:
  custom_lint:

  #Networking
  retrofit_generator: ^7.0.8

  #Assets
  flutter_gen_runner: ^5.3.1

  #Model
  freezed: ^2.4.1

  #Analyzer
  flutter_lints: ^2.0.2

  #Navigation
  auto_route_generator: ^7.3.1
  flutter_launcher_icons: ^0.13.1

  #Etc..
  change_app_package_name: ^1.1.0

flutter_gen:
  output: lib/gen/

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
