name: abo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  #    git:
  #      url: git@github.com:cenaclesoft/hana.git
  riverpod:
  riverpod_annotation:
  flutter_riverpod: ^2.6.1

  #Localization
  intl: ^0.19.0
  flutter_localization: ^0.2.2

  lottie:

  #Authentication
  supabase_flutter: ^2.8.0
  local_auth: ^2.1.7
  pinput: ^5.0.0

  #Utils
  collection: ^1.17.2
  encrypt: ^5.0.1
  crypto: ^3.0.6
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  path: ^1.8.3
  share_plus: ^10.1.2

  #Camera
  image_picker: ^1.0.4

  #Logger
  logger: ^2.0.2

  #Models
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  #Navigation
  auto_route: ^9.2.2

  #Network
  dio: ^5.3.2
  http: ^1.1.0
  retrofit: ^4.0.1

  #UI
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1

  #Notification
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  flutter_local_notifications: ^18.0.1

  #Else
  enum_to_string: ^2.0.1
  uuid: ^4.5.1
  url_launcher: ^6.1.7
  firebase_core: ^3.7.0
  screen_brightness: ^2.0.0+2
  infinite_scroll_pagination: ^4.0.0
  vector_math: ^2.1.4
  visibility_detector: ^0.4.0+2
  image: ^4.0.17
  file_picker: ^8.1.4
  file_selector: ^1.0.1
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  cloud_firestore: ^5.4.5
  table_calendar: ^3.1.2
  flutter_dotenv: ^5.2.1

# for test
#  device_preview: ^1.1.0


#dependency_overrides:
#  retrofit_generator:
#    path: ../generator

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  #Architecture
  riverpod_generator: ^2.2.6
  riverpod_lint:
  custom_lint:

  #Networking
  retrofit_generator: ^9.1.4

  #Assets
  flutter_gen_runner: ^5.3.1

  #Model
  freezed: ^2.4.1

  #Analyzer
  flutter_lints: ^5.0.0

  #Navigation
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.1

  #Etc..
  change_app_package_name: ^1.1.0

flutter_gen:
  integrations:
    flutter_svg: true

  output: lib/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
